### ISSUE TITLE
Agregar el campo "centro" y "edad" en los formularios para hacer consultas

### ISSUE THREAD

**Issue by danielcarranza** [datauy/derechosdelestudiante#1]
- [x] Poner los campos, como está en la versión actual. Nos explicaron que para ellos es fundamental saber de qué centro viene la consulta.

- [x] En el caso de consultas por UTU, sumar además el campo "Curso".

**Comment by agustinkry** [comment]
https://marvelapp.com/8cc0fb3/screen/57247554

**Comment by danielcarranza** [comment]
Tanto para éste como para el de denuncias, el campo "Curso" para UTU no sustituye "Centro", sino que se suma. Perdón que no se entendió.

**Comment by agustinkry** [comment]
done¡

**Comment by danielcarranza** [comment]
¡Lujo!
