### ISSUE TITLE
Ajustes formulario Denuncias

### ISSUE THREAD

**Issue by danielcarranza** [datauy/derechosdelestudiante#2]
- [x] El nombre cambia a "Denuncias Confidenciales"
- [x] Ponemos el mismo selector de "secundaria/UTU" que la búsqueda del home para saber quién canalizar
- [x] Sumamos los campos "centro" (y "curso" en el caso de UTU), "edad" 
- [x] Debajo del formulario vamos a poner un "Listado de recursos y otros medios para denuncias", donde vamos a listar cosas como:
  - Línea Azul (Violencia de Género), Teléfono
  - Comisaría de la Mujer (Violencia de Género), Teléfono
  - Línea de atención al suicidio MSP, Teléfono
  - Etc.

**Comment by agustinkry** [comment]
Secundaria
https://marvelapp.com/8cc0fb3/screen/56208677

UTU
https://marvelapp.com/8cc0fb3/screen/57247554

**Comment by agustinkry** [comment]
done

**Comment by danielcarranza** [comment]
Brillante
